# version management
---

# users to make members of microk8s group
users: [nss]

microk8s_version: "1.22/stable"
microk8s_disable_snap_autoupdate: false

microk8s_plugins:
  host-access: true                       # Allow Pods connecting to Host services smoothly
  ingress: true                           # Ingress controller for external access
  metrics-server: true                    # K8s Metrics Server for API access to service metrics
  rbac: true                              # Role-Based Access Control for authorisation
  storage: true                           # Storage class; allocates storage from host directory
  registry: "size={{ registry_size }}"    # Private image registry exposed on localhost:32000
  dashboard: true                         # The Kubernetes dashboard
  ambassador: false                       # Ambassador API Gateway and Ingress
  cilium: false                           # SDN, fast with full network policy
  fluentd: false                          # Elasticsearch-Fluentd-Kibana logging and monitoring
  gpu: false                              # Automatic enablement of Nvidia CUDA
  helm: false                             # Helm 2 - the package manager for Kubernetes
  helm3: true                             # Helm 3 - Kubernetes package manager
  istio: false                            # Core Istio service mesh services
  jaeger: false                           # Kubernetes Jaeger operator with its simple config
  knative: false                          # The Knative framework on Kubernetes.
  kubeflow: false                         # Kubeflow for easy ML deployments
  linkerd: false                          # Linkerd is a service mesh for Kubernetes and other frameworks
  metallb: false                          # Loadbalancer for your Kubernetes cluster
  multus: false                           # Multus CNI enables attaching multiple network interfaces to pods
  prometheus: false                       # Prometheus operator for monitoring and logging
  traefik: false                          # another ingress
  portainer: false                        # Container management dashboard
  keda: false                             # Kubernetes Event-driven Autoscaling operator.
  kata: false                             # A secure container runtime with lightweight virtual machines
  openebs: false                          # openebs storage
  openfaas: false                         # serverless


